name: football
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - libexpat=2.7.3
  - libffi=3.5.2
  - liblzma=5.8.1
  - libsqlite=3.51.1
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - python=3.11.14
  - readline=8.3
  - setuptools=80.9.0
  - tk=8.6.13
  - tzdata=2025c
  - wheel=0.45.1
  - pip:
      - hdbscan==0.8.41
      - joblib==1.5.3
      - llvmlite==0.46.0
      - narwhals==2.14.0
      - numba==0.63.1
      - numpy==2.3.5
      - packaging==25.0
      - plotly==6.5.0
      - pynndescent==0.5.13
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - umap-learn==0.5.9.post2
prefix: /Users/jcwiddaglizze/miniforge3/envs/football
